Add meson build system
grimme-lab/stda pull request #3
Opened 2019-12-12 14:01 UTC by pierre-24

**WIP**, do not merge.

A quick copy-paste-adaptation of the meson build system for `stda` (actually coming from `xtb4stda`), which can be used as an alternative to `make`. The 3 executable (`stda`, `g_spec` and `g2molden`) are compiled in the process. I'm currently checking if the binaries compiled by meson and make are producing the same output.

*Of course, since my goal is to compile `stda` on my cluster, I already included the `-Dstatic=false` option of https://github.com/grimme-lab/xtb/pull/40 so that it already works for me. Thus this PR will probably be delayed.* ;)

2019-12-12 14:06 UTC, pierre-24 commented
Or maybe #2 is a better solution ?

2019-12-12 15:22 UTC, awvwgk commented
@pierre-24 I always encourage using `meson` instead of `make`. #2 is a bit more than just `meson` support but also GCC support and continuous integration, which rely on having `meson` available.

I am curious, how do you cope with the dependency cycle in `stringmod.f90`?

2019-12-12 15:27 UTC, pierre-24 commented
I just saw that in your PR, but I have to say that for some reason, it does not break ninja for me (I'm using the latest ninja version, but it is from January of this year, so you should be using the same). Also, I only tried with intel, maybe it is linked.

2019-12-13 09:53 UTC, pierre-24 commented
Test done: with intel, no differences between the results obtained with the binary obtained through make and trough meson (without static linking, of course). Is the issue related to GCC?

2019-12-13 10:09 UTC, mdewergi commented
Yes, issues are gfortran specific. We will need time to look at these.  
Ok Pierre, thanks. I will test it next week and merge as well.

2019-12-14 15:31 UTC, awvwgk requested changes
There some inconsistencies in the README and between the README and the actual build file, that should be addressed before merging.

2019-12-14 15:31 UTC, awvwgk commented on README.md
> +To install the `sdta` binaries to `/usr/local` use (might require `sudo`)
`sdta` -> `stda`

2019-12-14 15:31 UTC, awvwgk commented on README.md
> +ninja -C build_intel install
was `intel_build` above, now it's `build_intel`.

2019-12-14 15:31 UTC, awvwgk commented on meson.build
> +        meson_version: '>=0.51')
if you require version 0.51 here, it should be stated in the README correctly. The real point is you aren't using 0.51 features and this `meson.build` is 0.49 compatible.

2019-12-14 15:31 UTC, awvwgk commented on meson.build
> +    libmkl += [fc.find_library('mkl_intel_lp64')]
no need for brackets here.

2019-12-16 08:23 UTC, pierre-24 commented
@awvwgk : fixed :)

2019-12-16 11:12 UTC, awvwgk approved these changes

2019-12-17 10:40 UTC, mdewergi approved these changes

2019-12-17 10:41 UTC, merged